"""Data quality anomaly reporter module.

Aggregates detected data quality anomalies across flights, passengers, bookings,
and payments, enforces strict PII masking, and outputs the Gold anomaly report.
"""

from pathlib import Path
from typing import List, Dict, Any
import pandas as pd

from src.config import GOLD_DIR


def generate_anomaly_report(
    anomalies: List[Dict[str, Any]],
    output_path: Path = GOLD_DIR / "data_quality_anomalies_report.csv",
) -> pd.DataFrame:
    """Consolidates anomalies, ensures strict PII masking, and writes the Gold report.

    Args:
        anomalies: List of anomaly dictionaries generated by cleaning steps.
        output_path: Destination path for the CSV report.

    Returns:
        DataFrame containing the consolidated anomaly records.
    """
    if not anomalies:
        df_anomalies = pd.DataFrame(columns=[
            "entity",
            "record_identifier",
            "field",
            "issue_type",
            "severity",
            "description",
            "whether_corrected",
            "safe_reference",
        ])
    else:
        df_anomalies = pd.DataFrame(anomalies)

    # Sort anomalies by severity and entity
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    df_anomalies["severity_rank"] = df_anomalies["severity"].map(severity_order).fillna(99)
    df_anomalies = df_anomalies.sort_values(["severity_rank", "entity", "record_identifier"]).reset_index(drop=True)
    df_anomalies.drop(columns=["severity_rank"], inplace=True)

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df_anomalies.to_csv(output_path, index=False)

    return df_anomalies
